[package]
name = "prooheckcp/example"
description = "A cleaner to handle connections and or object cleaning in your project"
version = "0.0.1"
license = "MIT"
authors = ["Prooheckcp"]
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = [
    "./..",
    "./../*"
]
realm = "shared"